# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httpcode < Formula
  desc "Minimal HTTP status code lookup tool support fuzzy search"
  homepage "https://github.com/lethang7794/httpcode"
  version "0.1.15"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/lethang7794/httpcode/releases/download/v0.1.15/httpcode_Darwin_x86_64.tar.gz"
      sha256 "4bcbe99396702dbe748602eba51cf30db586d87d4fe05a59825124d774b71df4"

      def install
        bin.install "httpcode"
        generate_completions_from_executable(bin/"httpcode", "completion")
      end
    end
    on_arm do
      url "https://github.com/lethang7794/httpcode/releases/download/v0.1.15/httpcode_Darwin_arm64.tar.gz"
      sha256 "b53136148fe8d2dffade193a18aa01cbc032d5f881d08ead4d7cde7b81052af1"

      def install
        bin.install "httpcode"
        generate_completions_from_executable(bin/"httpcode", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lethang7794/httpcode/releases/download/v0.1.15/httpcode_Linux_x86_64.tar.gz"
        sha256 "df519927d4bdb80423470110f96c27019e67da5247b67a5537d9f3b877ce614d"

        def install
          bin.install "httpcode"
          generate_completions_from_executable(bin/"httpcode", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lethang7794/httpcode/releases/download/v0.1.15/httpcode_Linux_arm64.tar.gz"
        sha256 "9d34749778d199bb1a2766559842543ac6264cf23769c1b850e24caadf3dc252"

        def install
          bin.install "httpcode"
          generate_completions_from_executable(bin/"httpcode", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/httpcode --help"
    system "#{bin}/httpcode version"
  end
end
