# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httpcode < Formula
  desc "Minimal HTTP status code lookup tool support fuzzy search"
  homepage "https://github.com/lethang7794/httpcode"
  version "0.1.10"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/lethang7794/httpcode/releases/download/v0.1.10/httpcode_Darwin_x86_64.tar.gz"
      sha256 "ad8f79eb919e557b96c9782dc7dc4bd7a1bb9e55bd8a1c53c03772ac98d0d729"

      def install
        bin.install "httpcode"
      end
    end
    on_arm do
      url "https://github.com/lethang7794/httpcode/releases/download/v0.1.10/httpcode_Darwin_arm64.tar.gz"
      sha256 "486f27e056ddde3b7e43ac4903dba33ab1e0210f611af716659cb9eb98a174a1"

      def install
        bin.install "httpcode"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lethang7794/httpcode/releases/download/v0.1.10/httpcode_Linux_x86_64.tar.gz"
        sha256 "4f56e068470c1986f74e0848585944684d20100bcb92727a1b8d89c2e1ae4172"

        def install
          bin.install "httpcode"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lethang7794/httpcode/releases/download/v0.1.10/httpcode_Linux_arm64.tar.gz"
        sha256 "c2d91936fab2c0b5b632c01be29a18cef323b80d3c29760903b1c942e004482e"

        def install
          bin.install "httpcode"
        end
      end
    end
  end

  test do
    system "#{bin}/httpcode --help"
    system "#{bin}/httpcode version"
  end
end
