# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httpcode < Formula
  desc "Minimal HTTP status code lookup tool support fuzzy search"
  homepage "https://github.com/lethang7794/httpcode"
  version "0.1.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/lethang7794/httpcode/releases/download/v0.1.11/httpcode_Darwin_x86_64.tar.gz"
      sha256 "a617f42fe4eac17c4605d1d09c55b59200f1b8ff6a59dd0e566b1fc10e171ae0"

      def install
        generate_completions_from_executable(bin/"httpcode", "completion")
      end
    end
    on_arm do
      url "https://github.com/lethang7794/httpcode/releases/download/v0.1.11/httpcode_Darwin_arm64.tar.gz"
      sha256 "9adf0d101161470a240e0c1165bffe8698ca06704ee226446ee7ffd72d52f516"

      def install
        generate_completions_from_executable(bin/"httpcode", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lethang7794/httpcode/releases/download/v0.1.11/httpcode_Linux_x86_64.tar.gz"
        sha256 "a9c2564800e6cef6e390336878066ec54174e392a900b5eb596e7f0e94225ee0"

        def install
          generate_completions_from_executable(bin/"httpcode", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lethang7794/httpcode/releases/download/v0.1.11/httpcode_Linux_arm64.tar.gz"
        sha256 "54d7a177cd2e419c52cd8786e5d5c7daedf2f2129fb037298b1d1b9c0a5c7d8d"

        def install
          generate_completions_from_executable(bin/"httpcode", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/httpcode --help"
    system "#{bin}/httpcode version"
  end
end
